### ISSUE TITLE
File Save Error for jupyter notebook

### ISSUE THREAD

**Issue by ranchen2025** [det-lab/jupyterhub-deploy-kubernetes-jetstream#11]
The error info is in the picture. It will show up every time the jupyter notebook wants to save it automatically or I click on save.
![save_error](https://user-images.githubusercontent.com/62438622/77190970-2f5e9880-6aa8-11ea-85b1-676b81ec00b0.png)

**Comment by pibion** [comment]
Thanks for the issue @ranchen2025!  You may want to @zonca on such posts, this issue didn't automatically show up in my email.

**Comment by zonca** [comment]
please upload the notebook to http://gist.github.com

and if you need some input data, please also explain me how to get them.

I think the problem is that your notebook is too big.

**Comment by pibion** [comment]
@ranchen2025 could you post links to your data repository and notebook repository?

**Comment by ranchen2025** [comment]
Hello,
Sorry for the late reply.
The link of the repository include my notebook and data is:
https://github.com/ranchen2025/NR5.git
Will this work?

Best regards,
Ran Chen

**Comment by pibion** [comment]
@ranchen2025 I can access those, thanks!

**Comment by zonca** [comment]
First time I see a Notebook with more than 100 cells,
I think JupyterLab cannot save it because once you produce the plots, it is several MB.
Is there a reason it is so long instead of creating more smaller notebooks?

Can you test with smaller notebooks and see if you find the same issue?

**Comment by ranchen2025** [comment]
Hello,

Thanks! Your advice does help a lot.
The issue doesn't show up after I use smaller notebooks. I will avoid make
so large notebook in the future.

Best regards,
Ran Chen

**Comment by zonca** [comment]
actually there is probably a fix, see https://github.com/jupyterlab/jupyterlab/issues/4214,
I'll try to implement this in the setup.

**Comment by zonca** [comment]
@ranchen2025 @pibion I've increased the size to 20 MB, so it should not cause problems even with very large notebooks.

**Comment by blackholesun137** [comment]
I'm still having issues with text files above a certain size. I've tried uploading a 15 MB text file, as well as opening a blank text file in Jupyter, copy-pasting the data there, and trying to save, but, in either case, I get the error, "Invalid response: 413 Request Entity Too Large." I have been able to upload a 1 KB text file, so the issue can't be with text files in general.

**Comment by zonca** [comment]
confirmed.
I guess there is some margin.
I increased the limit from 20MB to 100MB and successfully uploaded a 16MB PDF. can you try again?

**Comment by blackholesun137** [comment]
I was able to upload it this time. Thank you.
