### ISSUE TITLE
Instance takes a long time to spin up (or does not spin up)

### ISSUE THREAD

**Issue by pibion** [det-lab/jupyterhub-deploy-kubernetes-jetstream#16]
I'm trying to access a JupyterHub instance, but it seems to be taking a very long time to spin up.

Is anyone else having this issue? @zonca @ziqinghong

**Comment by zonca** [comment]
I know they were updating some of the services on Jetstream today, I'll check the deployment later today and then get back to you.

**Comment by zonca** [comment]
same issue I encountered in #10, let's continue debugging in that issue, I'll close this one.

**Comment by pibion** [comment]
@zonca when trying to access https://supercdms.jetstream-cloud.org I'm able to authenticate but the server takes a long time to spin up.

Actually, it hasn't spun up yet so I'm not sure if it's able to.  I'll report back when I get an error or it completes.

**Comment by zonca** [comment]
I see your pod running, you cannot access it?

**Comment by zonca** [comment]
I found the problem, while developing I had setup that the docker image of the container is pulled everytime.
Now back to normal, so it should start a lot quicker

**Comment by pibion** [comment]
Yes, this spawned quickly for me!

**Comment by pibion** [comment]
Hi @zonca , one of our users is having trouble spinning up an instance.  I've attached her message and images.

> I've run into some difficulties with accessing JupyterHub/Jetstream. I have tried relaunching the server several times-- just in case it may have been my internet connection being slow. I am currently receiving the same messages each time I refresh (Attached below). I'm not sure if it has to do with the recent update or something on my side. 

![JupyterHubServerStart2](https://user-images.githubusercontent.com/1872784/86041771-662b3f80-ba03-11ea-994e-945695d80d52.png)
![JupyterHubServerStart1](https://user-images.githubusercontent.com/1872784/86041772-66c3d600-ba03-11ea-8f6b-0af7eb646d7d.png)

**Comment by zonca** [comment]
yes, I see all the persistent volumes have been deleted.
Now I would like to understand why that happened.
After I redeployed on Thursday around noon Pacific (https://github.com/det-lab/jupyterhub-deploy-kubernetes-jetstream/issues/28#issuecomment-650011693) has anyone tested JupyterHub, did they see their old data?

**Comment by zonca** [comment]
@pibion, anyway I reset the volumes, now it should work fine for all users. Can they try again?

**Comment by pibion** [comment]
@jpanmany466, could you try to access JupyterHub again and let us know if you see your existing files?

**Comment by zonca** [comment]
@pibion next time please open a new issue to report anything not working, even if symptoms are similar, most of the time errors are unrelated. That helps me keep track of things. Thanks.

Existing files are definitely gone, I'm sorry about that, something went wrong either in my redeployment or something happened afterwards. I'll be sure I ask someone to test just after I redeploy next time.

**Comment by pibion** [comment]
@zonca re issues: sounds good, will do.  I'll contact the student and see if they need any help setting up again.

**Comment by zonca** [comment]
I think this is fixed, if not please open another issue
