### ISSUE TITLE
Setup permanent domain name

### ISSUE THREAD

**Issue by zonca** [det-lab/jupyterhub-deploy-kubernetes-jetstream#17]
I think we are at a good point in testing the deployment,
we can start to think about setting up a permanent URL.
Does CDMS or your institution have a procedure to set that up?
Or shoud I investigate if we can get a *.xsede.org domain?

**Comment by pibion** [comment]
A *.xsede.org domain would be fantastic.

UC Denver doesn't have a procedure for setting up domain names, but someone else in the collaboration might have that ability.  I can ask around if and xsede domain isn't an option.

**Comment by zonca** [comment]
ok, written to XSEDE, will update here when I have news.

**Comment by zonca** [comment]
* they don't do xsede.org subdomains
* the jetstream team doesn't usually do subdomains, but they can make an exception for us, so we can have `supercdms.jetstream-cloud.org` (a bit long)
* otherwise I can easily get a sdsc subdomain, which is not as relevant but it is short `supercdms.sdsc.edu`
* other options? doesn't the CDMS collaboration have any 1st level domain they manage? or if you have other uses or it, you can register a new domain, then we can point jupyter.newdomain.org to that.

**Comment by pibion** [comment]
@zonca `supercdms.jetsream-cloud.org` would be my first choice, but I don't want to create extra work for you or the Jetstream team.

If it's a hassle, let me know and I'll register `supercdms.tk`?

**Comment by zonca** [comment]
ok, I submitted a request for the jetstream-cloud subdomain

**Comment by zonca** [comment]
ok, setup https://supercdms.jetstream-cloud.org/
works fine with SSL certificates by letsencrypt.

Now that we have authentication setup, we do not need to keep the URL secret.
