### ISSUE TITLE
Losing data in personal space

### ISSUE THREAD

**Issue by pibion** [det-lab/jupyterhub-deploy-kubernetes-jetstream#22]
@thathayhaykid and I are running into an issue with lost data:

Files saved to `/home/jovyan` and `/home/jovyan/work` disappear when the server is restarted.

**Comment by zonca** [comment]
yes, see the warning at https://github.com/det-lab/jupyterhub-deploy-kubernetes-jetstream/issues/20
I haven't fixed it yet.
