### ISSUE TITLE
Site Cannot Be Reached

### ISSUE THREAD

**Issue by GabriellaNicoleRamirez** [det-lab/jupyterhub-deploy-kubernetes-jetstream#24]
When trying to access https://supercdms.jetstream-cloud.org/ I get a "Site cannot be reached" error. Perfectly fine internet connection.

Any help would be appreciated, thanks!

**Comment by zonca** [comment]
Yes, It is unreachable I am investigating I will let you know

**Comment by zonca** [comment]
ok, it was reset by mistake by Josh, I started to redeploy it again, will let you know once it is back online.

**Comment by pibion** [comment]
Just checking in on this issue - the site still isn't responding.

**Comment by zonca** [comment]
There is now an issue on the Jetstream platform, unrelated to the reset, and I cannot redeploy. They are working on a fix. I'll update this issue once I am able to proceed.

**Comment by zonca** [comment]
they haven't yet fixed the issue on Magnum.
So I have switched to the other deployment strategy using Kubespray https://zonca.dev/2018/09/kubernetes-jetstream-kubespray.html
I already have a cluster running, I'll configure it for CDMS in the next days and update you here.

**Comment by zonca** [comment]
ok, it is back up.
I have deployed with a different strategy, I tested:

* launch notebook
* that the data in the /cvmfs/data volume is still there
* install_cdms_kernels works

only strange is the popup asking to rebuild jupyterlab, see https://github.com/det-lab/jupyterhub-deploy-kubernetes-jetstream/issues/25, **just click `cancel`**

if there is anything else broken please open another issue.

@pibion
