### ISSUE TITLE
`ls /cvmfs` takes a long time

### ISSUE THREAD

**Issue by pibion** [det-lab/jupyterhub-deploy-kubernetes-jetstream#28]
I hadn't noticed this behavior before, so maybe the issue is that there's now more data in the directory?  Here is an output showing the issue:

```bash
bash-4.2$ time ls
lost+found

real    0m0.005s
user    0m0.005s
sys     0m0.000s
bash-4.2$ time ls /cvmfs/data
CDMS  lost+found  not_writable  test_file  test_file_2  tf

real    0m40.055s
user    0m0.000s
sys     0m0.007s
```

**Comment by zonca** [comment]
Where are you running from?

**Comment by zonca** [comment]
Debugging this, if I run locally inside the pod, it is very fast:

```
[root@cvmfs data]# time ls
CDMS  lost+found  not_writable  test_file  test_file_2  tf

real    0m0.004s
user    0m0.003s
sys     0m0.001s
```

Instead if I connect to JupyterHub and connect to that, it is very slow.

so it is the NFS server, I'll take a look.

**Comment by zonca** [comment]
Tried launching a different standalone pod with https://github.com/det-lab/jupyterhub-deploy-kubernetes-jetstream/blob/master/cvmfs/test_nfs_mount.yaml

and there `ls` is actually very fast, so there must be something problematic about the Jupyter pods or the Jupyterlab terminal.

**Comment by zonca** [comment]
ok, I restarted the pod and now it is very fast.
However I don't know what was wrong so it will probably happen again.
Please reopen the issue when that happens and I'll try to debug more deeply.

**Comment by zonca** [comment]
I see it is slow again, I'm checking what is going on

**Comment by zonca** [comment]
The cache disk is full.

`dev/sdd         20G   20G     0 100% /var/lib/cvmfs`

**Comment by zonca** [comment]
creating the service again with a cache folder of 200GB

**Comment by pibion** [comment]
@zonca are we doing something non-optimal that's causing the cache folder to get large?

**Comment by zonca** [comment]
@pibion no I think it is normal, I'll monitor cache size.

However now that I restarted the service, the pods cannot connect to NFS anymore. Debugging that.

**Comment by zonca** [comment]
@pibion actually the NFS server is fine,
it is instead an issue in Kubernetes that cannot mount the NFS shares.
I could try to debug this issue, however, this deployment has a old version of Kubernetes, I'd rather use the new deployment I have been working on.
Only then, if the issue persists, I will debug it.

I see:

* `herogers924`
* `jpanmany466`

connected, can you check with them if I can proceed to wipe the deployment and redeploy?
I'll keep the data in `/cvmfs/data`, I'll wipe the user home folders.

**Comment by pibion** [comment]
@zonca, would it be possible to restore at least the local user data for `jpanmany466`?

She's a student and has only just gotten her ssh keys and local repositories set up.

**Comment by zonca** [comment]
Ok

**Comment by pibion** [comment]
@zonca awesome, thank you!  In the meantime I'll check that they've recently committed so that if anything is lost it's not too troublesome to recover.

**Comment by zonca** [comment]
ok, I have redeployed, saved the user volumes (hope it worked fine),
added docs about that procedure to [REDEPLOY.md](https://github.com/det-lab/jupyterhub-deploy-kubernetes-jetstream/blob/master/REDEPLOY.md)

I'm closing this issue for now, let's see how it goes in the next days.
