### ISSUE TITLE
uploading files to JupyterHub - increase file limit?

### ISSUE THREAD

**Issue by pibion** [det-lab/jupyterhub-deploy-kubernetes-jetstream#31]
Several people have tried to upload data files (larger than 100 MB, less than 1 GB) but have run into "file too large to upload" errors.

Is it possible (and wise) to increase this limit?

**Comment by zonca** [comment]
I set 100MB back in #11.
I don't recommend using the browser upload for 1GB files, it would be way better to open the terminal and use ssh or rsync.
Anyway, it is a easy fix, I can bump it up to 1GB for convenient.

**Comment by zonca** [comment]
ok, I increased it to 1GB,
then I tested uploading a ~550 MB file,
I am quite impressed with the Jupyter uploader, it seems very fast and reliable, and minimal resource usage.
it also has a progress bar.

![image](https://user-images.githubusercontent.com/383090/86717979-83e63f00-bfd7-11ea-9ff5-a9496b71048c.png)

So it might work for bigger files, I increased the limit to 10 GB

**Comment by zonca** [comment]
btw, I find it very useful to ask about usability improvements, @pibion, they are often quick fixes for me but very useful for the users.
