### ISSUE TITLE
Rebuilding the user images

### ISSUE THREAD

**Issue by zonca** [det-lab/jupyterhub-deploy-kubernetes-jetstream#32]
I started to update the user images, my work is based on the images released by the Jupyter team:

https://github.com/jupyter/docker-stacks

but modified to be based on Centos 7 instead of Ubuntu:

https://github.com/zonca/jupyter-docker-stacks-centos7

So we will get a newer version of JupyterLab, and I'll try to fix #25 and #27 

I'll notify when it this is deployed.

**Comment by zonca** [comment]
the updated images are larger, because they also have the Latex environment which is used by nbconvert, I could remove that. However we are using very large Jetstream instances, so we should be fine.

```
REPOSITORY                                                       TAG                 IMAGE ID            CREATED             SIZE
jupyter/tensorflow-notebook                                      latest              003e43057ac0        3 minutes ago       3.7GB
jupyter/scipy-notebook                                           latest              e8bf31e11f34        9 minutes ago       2.05GB
jupyter/minimal-notebook                                         latest              6d2d8bbdafee        15 minutes ago      1.24GB
jupyter/base-notebook                                            latest              4403d4c9970c        About an hour ago   846MB
```

**Comment by zonca** [comment]
ok @pibion, this is deployed, please let me know if there are issues.
It also has the `jupyterlab-system-monitor`

![Screenshot 2020-07-07 at 00 18 20](https://user-images.githubusercontent.com/383090/86735709-d596c580-bfe7-11ea-970a-d5f9401e645a.png)

also it would be useful if you create a group under the organization https://github.com/orgs/det-lab/people with all the users of the Jetstream deployment (named @jetstream-users or similar) so I can notify everybody about news on the deployment.

**Comment by zonca** [comment]
ok, this seems to work fine, I'll investigate #27 next

**Comment by pibion** [comment]
@zonca I've made a jetsream-users team, but it seems you have to be a member of the det-lab organization for me to add you.

Does that sound right to you?  I'm wondering if I'm missing a different type of grouping.

**Comment by zonca** [comment]
@pibion yes, right teams are just for organization members.
We can do 2 ways, either is fine for me:
* leave me out of that team, after all, it is mostly useful for me to reach to them. only annoyance is for example if you want to communicate something you have to tag @jetstream-team and @zonca 
* add me to the organization and to the team, (unless you have sensitive data in some repos, then better not)

**Comment by zonca** [comment]
@pibion, actually option 1 won't work, I cannot tag the team if I am **not** member of organization.
So if you don't have sensitive data and can do option 2 good, otherwise nevermind.
