### ISSUE TITLE
ip addresses for whitelisting?

### ISSUE THREAD

**Issue by pibion** [det-lab/jupyterhub-deploy-kubernetes-jetstream#33]
In our collaboration we sometimes whitelist ranges of IP addresses for easier access to collaboration resources.

Is there a range of IP addresses for the JupyterHub instances people spin up that we could ask our colleague to whitelist?

**Comment by zonca** [comment]
I think 149.165.*.* should work.

**Comment by pibion** [comment]
Hi @zonca , from our admin:

> 149.165... is all of Indiana University, with 65536 IPs.  Is there a smaller set of IPs that just covers XSEDE?

**Comment by zonca** [comment]
@jlf599 quick question: what is the IP range of Jetstream?

**Comment by zonca** [comment]
Got it, thanks @jlf599,
@pibion, better not post publicly, I'll email you
