### ISSUE TITLE
Cannot start JupyterLab session

### ISSUE THREAD

**Issue by pibion** [det-lab/jupyterhub-deploy-kubernetes-jetstream#36]
@jpanmany466 is having difficulty starting a JupyterLab session - the complaint it returns is that the spawner is timing out:

![spawner_timeout](https://user-images.githubusercontent.com/1872784/88089122-be5bea00-cb48-11ea-9d2f-a0fad7cb3622.png)

**Comment by pibion** [comment]
Interestingly, I was able to start @jpanmany466 server from the admin tab.

She's now trying to start her server again to see if the issue is reproducible.

**Comment by zonca** [comment]
it looks like a timeout in mounting the NFS volume, I wonder if it is related to https://github.com/det-lab/jupyterhub-deploy-kubernetes-jetstream/issues/28
I'm running a test

**Comment by pibion** [comment]
@zonca thanks!  I just confirmed with @jpanmany466 that she was able to spin up a server, so this is either intermittent or one-time.

**Comment by zonca** [comment]
ok, I checked the NFS server and the speed of `ls` and it seems fine. Please reopen the issue if it happens again.

**Comment by pibion** [comment]
Will do!
