### ISSUE TITLE
JupyterLab spawning failure

### ISSUE THREAD

**Issue by pibion** [det-lab/jupyterhub-deploy-kubernetes-jetstream#38]
@jpanmany is running into spawning issues again:

![spawn_fail2](https://user-images.githubusercontent.com/1872784/88697754-56fee680-d0c2-11ea-9878-73ac1c4b407e.png)

This time it looks like the issue is that she doesn't have ssh keys, and the script is failing when it tries to set permissions.

**Comment by zonca** [comment]
Of course, silly me, I didn't think about .ssh missing, working on it

**Comment by zonca** [comment]
Ok, should be fixed now, can you cross-check and close issue if ok?

**Comment by pibion** [comment]
@jpanmany reports success!  Thanks @zonca!
