### ISSUE TITLE
Access CVMFS from pods?

### ISSUE THREAD

**Issue by zonca** [det-lab/jupyterhub-deploy-kubernetes-jetstream#4]
@pibion I was thinking we could evaluate at some point how difficult it would be to setup CVMFS access for JupyterHub users:

https://cernvm.cern.ch/portal/filesystem

Let's first finalize the work on the JupyterHub deployment and then consider if we should add this to the workplan.

## Documentation

* https://twiki.cern.ch/twiki/bin/view/AtlasComputing/Cvmfs21#Hard_mount_cvmfs_and_nfs_export

**Comment by pibion** [comment]
That sounds like an excellent plan, thanks for suggesting this!

**Comment by zonca** [comment]
@pibion  Do you have any pointers to documentation about accessing CVMFS for CDMS?

**Comment by bloer** [comment]
I'm the cvmfs maintainer.  Things are scattered, so I will add centralizing some documentation to my to-do list.  In the meantime, assuming CVMFS is set up with oasis,  you can do
`/cvmfs/cdms.opensciencegrid.org/setup_cdms.sh -L `
to list available releases and 
`source /cvmfs/cdms.opensciencegrid.org/setup_cdms.sh V01-02-01`
which gets the latest version as of today.  Only bash is supported right now.

**Comment by zonca** [comment]
thanks @bloer that does work on Comet.
* how do I test a random command to check it executes fine?

Then about the deployment on Jetstream, inside JupyterHub each user has a Docker container running on a number of different Jetstream Fedora virtual machines.
I am not familiar with CVMFS. Do you recommend each single user container have the CVMFS client? or should we have a dedicated Jetstream VM to run the CVMFS client and give access some other way to the clients? (NFS or similar)

**Comment by bloer** [comment]
@zonca It's not a great test, but an easy check is to just run "BatRoot" (should be in the path).  If you get a help message rather than complaints about missing libraries/symbols, it should be good. 

I only have passing familiarity with setting up CVMFS itself; I handle deploying the CDMS part of it.   There are a few considerations.  

You're encouraged to point your CVMFS client at a local SQUID proxy rather than at the central CVMFS servers.  If we're currently concerned only about running at SLAC, we should be able to put the client on each container and point at SLAC's SQUID server; probably copying the whole /etc/cvmfs configuration directory from a node there would work.  In the long run if this will be running on other sites, that obviously won't work.  Probably we can get away with a handful of direct clients, but it will be slower.  The proxy setting does allow for failover, so maybe that's the best way to go.  

When we pull in CVMFS, we pull in a huge number of dependencies for convenience.  We could probably streamline it a bit, but it would take a decent amount of effort and probably be significantly less stable.  I don't know just how much data actually gets pulled in, but I'm guessing it's order GB.  Can the VMs handle that amount of disk use for every image?   

Finally, if the Docker images will be published at the same pace as CVMFS releases, it might make sense to just make all of that part of the image, rather than having to download it every time as soon as the image is spun up.  But that wouldn't work if we get to the point where the Docker image is stable and the software is delivered through moving CVMFS targets.

**Comment by zonca** [comment]
thanks, I think the best would be to have a local SQUID running on Jetstream, then have the user pods point to that.
do you happen to have a docker container already pre-configured for that? or can you send me the configuration for your SQUID proxy so I can replicate that on Jetstream?

**Comment by zonca** [comment]
## CVMFS client test on Jetstream

### Have pod running CVFMS client and NFS Server

Based on https://github.com/opensciencegrid/docker-osg-wn/blob/3.5/Dockerfile but using `osg-oasis`, see https://opensciencegrid.org/docs/worker-node/install-cvmfs/

Needs to run privileged due to `autofs`

### Use NFS to mount to Jupyter Notebook containers

https://cvmfs.readthedocs.io/en/stable/cpt-configure.html#nfs-server-mode

**Comment by zonca** [comment]
Attempt at dockerfile, not working yet because autofs is not running as a service, here for future reference:

```
FROM centos:centos7

LABEL name="OSG 3.5 Worker Node Client on EL 7"
LABEL build-date="20200128-1035"

RUN yum -y install https://repo.opensciencegrid.org/osg/3.5/osg-3.5-el7-release-latest.rpm \
                   epel-release \
                   yum-plugin-priorities && \
    yum -y install  \
                   osg-oasis \
                cvmfs-config-default \
                   redhat-lsb-core \
                   singularity && \
    yum clean all && \
    rm -rf /var/cache/yum/*
```

**Comment by zonca** [comment]
ok, @pibion, this works great!
I have a container which mounts the CDMS files on CVMFS: https://github.com/zonca/docker-cvmfs-client

So 1 instance of this can run **inside** Kubernetes on Jetstream. Next week I will work on a way for the Jupyter Notebook pods to access these files (possibly NFS). So we have just 1 CVMFS client, I think we don't need a proxy as once the software stack is cached on this repo, all the Jupyter Notebook users will just access it.

If this works, then in #3 we can go for a lightweight container.

**Comment by pibion** [comment]
Looks like it's time for me to learn more about CVMFS :)

**Comment by bloer** [comment]
By the way, there's a potential pitfall with cvmfs over nfs.  The way CVMFS is setup with automount means that repos are not downloaded until they are accessed.  I don't know that when you call `setup_cdms.sh` all the libraries needed are downloaded, or if some will still need to be loaded on demand.  Nor do I know if things get automatically unloaded at some point.  

So if you have one client and share everything over nfs, you may run into situations where the initial setup seems to work but then later fails.

**Comment by zonca** [comment]
thanks @bloer, sure we will test that, they have a specific mention of NFS sharing in the docs https://cvmfs.readthedocs.io/en/stable/cpt-configure.html#nfs-server-mode, so I hope it will just work.

**Comment by rptaylor** [comment]
Hello,
I came across this following up from a Compute Canada - SuperCDMS collaboration about Jupyter on Kubernetes. At Compute Canada (UVic) we have a kubernetes cluster running HEP jobs that access CVMFS. Installing a CVMFS client in every container is possible, gives you more direct control over the configuration at the pod user level, and is an easy/quick way to get started with small scale testing, but it means that every pod will have a separate independent CVMFS cache, leading to maximal duplication of data storage and disk IO and minimal benefits of cache sharing, which would not be suitable for large scale use. Also, as the documentation describes the NFS server mode is not ideal for performance and reliability reasons.

To access CVMFS in Kubernetes I would recommend either of two approaches:
- use the cvmfs-csi driver: https://github.com/cernops/cvmfs-csi  This runs as a daemonset so there is only one CVMFS client per underlying node, with a shared cache for all pods on the node. It uses the Kubernetes CSI interface to provide repository access to pods as volumes. This way CVMFS is contained inside the application layer of the kubernetes cluster.
- Install CVMFS on the underlying nodes of the cluster (if you have access to and control of the infrastructure) and provide hostPath volumes to the pods, and use a PodSecurityPolicy to limit read access to only /cvmfs .  

Sounds like we will have some recurring meetings starting soon so we can discuss further then.

**Comment by rptaylor** [comment]
There are some interesting possibilities for distributing the container images themselves with CVMFS too.

**Comment by zonca** [comment]
thanks @rptaylor!
* I looked at `cvmfs-csi` already, it has so few commits, old pull requests not addressed, I wouldn't want to rely on that.
* `hostPath` would be a good option. But I am creating the nodes with Magnum, so I don't have much control on those.
* I think we should test NFS first, we are on local network with only a few tens of clients.

**Comment by rptaylor** [comment]
@zonca Okay, as far as I know the cvmfs-csi driver works fine and is being used in production, and there are no open issues. But I will check with the developers if any of those old pull requests are still relevant or waiting.

**Comment by zonca** [comment]
Last week I got the CVMFS container working inside Kubernetes, see the pod definition at:

https://github.com/zonca/jupyterhub-deploy-kubernetes-jetstream/tree/master/cvmfs

Now I'm working on the NFS server, plan is to have a 2-container pod with a shared volume.

**Comment by zonca** [comment]
A shared volume doesn't work, because it is not a normal filesystem, we need to run the NFS server in the same container that runs the CVMFS client.

Testing it at: https://github.com/zonca/docker-cvmfs-client/tree/master/cvmfs-client-nfs

**Comment by zonca** [comment]
ok, CVMFS + NFS is working fine.

@rptaylor @pibion I wrote some notes about this, can you please provide feedback? https://zonca.github.io/2020/02/cvmfs-kubernetes.html

You can directly edit it at: https://github.com/zonca/zonca.github.io-source/blob/master/content/kubernetes_cvmfs.md

**Comment by rptaylor** [comment]
@zonca Okay, glad to hear you got it working. I checked with the cvmfs-csi developers and some other people using it, while there could be some improvements made, as far as I know it nevertheless still works fine and there are no major outstanding issues. If anything is missing from the documentation perhaps you could open an issue or contact them to ask for clarification. That being said if scalability is not a concern the NFS way should also work.

**Comment by zonca** [comment]
@rptaylor thanks, let's reconsider this if we hit scalability or reliability issues.

**Comment by pibion** [comment]
@zonca apolgoies for the radio silence, I'll have a chance to spend time on this early next week!

**Comment by zonca** [comment]
@rptaylor I am now using `DIRECT`,  can you please find out if any institution close to Indiana University has a CVMFS proxy we can use (or point me in the right direction)?

**Comment by rptaylor** [comment]
@zonca It rather depends on what repositories you are using, and for which experiments. I believe Indiana is involved in ATLAS; probably if you check with your physics department they may have info about a Tier 3 or Tier 2 site with squid proxies you could share, at least if it is HEP related.

Also the stratum servers for some repos/organizations use a commercial CDN which is kind of equivalent to using squids.

Moreover, although the NFS client is a bottleneck and single point of failure, on the plus side it also means you effectively have only a single CVMFS client so it's probably generally acceptable to use DIRECT, whereas a cluster of multiple clients should share a squid.

**Comment by zonca** [comment]
thanks @rptaylor, I am using the CDMS repos and its dependencies, I am in San Diego so don't have contacts in Physics at IU.

Anyway, for now let's keep using DIRECT and reconsider later on.

**Comment by zonca** [comment]
ok, this is solved for now, now will test within JupyterHub
