### ISSUE TITLE
new spawn fails to start in 600 seconds

### ISSUE THREAD

**Issue by pibion** [det-lab/jupyterhub-deploy-kubernetes-jetstream#45]
One of our users is getting a "failing to start in 600 seconds" error when trying to log in to JupyterHub.  Picture below.

![Screen Shot 2020-11-16 at 13 55 56](https://user-images.githubusercontent.com/1872784/99298380-df86cb80-2806-11eb-971a-2616a8d7cabb.png)

**Comment by zonca** [comment]
my bad, when I reboot the head node I need to also reboot the other node otherwise the internal network stops working.

**Comment by zonca** [comment]
added reference to this problem in the docs

**Comment by zonca** [comment]
ok I see `jupyter-mbaiocchi` running fine now
