### ISSUE TITLE
Update Jupyterlab in user container

### ISSUE THREAD

**Issue by zonca** [det-lab/jupyterhub-deploy-kubernetes-jetstream#53]
We have now Jupyterlab 2.x on the user images,
I am testing Jupyterlab 3, the nice thing is that now it is a lot easier to install extensions because they are simple python packages.

**Comment by zonca** [comment]
I am testing the builds on DockerHub, I haven't deployed anything yet, will keep track here of progress.

**Comment by zonca** [comment]
see https://github.com/zonca/docker-jupyter-cdms-light/commit/59caadae153f20fe958a3321a7e6f96747aadb06

the log of the update in conda:

https://gist.github.com/246a97dbac65e8b1db05efb10bd7f118

**Comment by zonca** [comment]
build logs on dockerhub: https://hub.docker.com/repository/docker/zonca/docker-jupyter-cdms-light/builds/e259ccd1-31ba-4a60-826d-830b0a96605f

**Comment by zonca** [comment]
tagged image `2021.03.12`

**Comment by zonca** [comment]
it gives "need to rebuild `jupyter-matplotlib` extension" error, trying to add `ipympl` package to container

**Comment by pibion** [comment]
Just here to confirm that I also get this error!

**Comment by zonca** [comment]
no adding `ipympl` didn't help.

the exact error is: `jupyter-matplotlib needs to be included in build`

**Comment by zonca** [comment]
ok, I think the problem is that I have a version of `ipympl` which is too old:

     ipympl                    0.5.6              pyh9f0ad1d_1    conda-forge

however, the conda version resolver cannot upgrade it due to other contraints

**Comment by zonca** [comment]
ok, I found a fix, I need to also update `ipywidgets`, testing it soon

**Comment by zonca** [comment]
ok, that fixed the issue, I have temporarily disabled latex to speedup my testing, tomorrow once the container is built by DockerHub I'll restore that and notify here.

**Comment by zonca** [comment]
ok, I restored the container with Latex, this is completed.
