### ISSUE TITLE
Unsure how to change machine allocation

### ISSUE THREAD

**Issue by zkromerUCD** [det-lab/jupyterhub-deploy-kubernetes-jetstream#54]
I started working with a tiny server option (1 CPU), but then realized that I needed a default server option (4 CPUs). However, I am unsure how to change the machine allocation from tiny to default.

**Comment by zonca** [comment]
you cannot change it, you need to go to your control panel https://supercdms.jetstream-cloud.org/hub/home
stop your server and start it again
