### ISSUE TITLE
White screen when opening XSEDE Resource

### ISSUE THREAD

**Issue by thathayhaykid** [det-lab/jupyterhub-deploy-kubernetes-jetstream#56]
Hi there!

I'm trying to access the XSEDE resource and I'm finding that all I get is a white screen, no matter what I do!

Is there something we can do to fix this?

Thank you!

-Haythem Mansour
![Screen Shot 2021-05-25 at 2 01 29 PM](https://user-images.githubusercontent.com/12423317/119560985-dbada600-bd61-11eb-9f16-ff608d6fb127.png)

**Comment by zonca** [comment]
is that after you login or before? Do you have a adblocker you can disable?

**Comment by zonca** [comment]
or do you have another browser you can try? It seems a browser issue

**Comment by zonca** [comment]
No feedback, closing this, please reopen if needed
