### ISSUE TITLE
Quota issue on backup

### ISSUE THREAD

**Issue by zonca** [det-lab/jupyterhub-deploy-kubernetes-jetstream#57]
@pibion I am investingating errors in backing up the volumes.
I think it is a quota issue on OSN.

Here is the error I get if I try to upload manually a small file to the SuperCDMS OSN:

```
> aws s3 --profile osn cp license.txt s3://supercdms-data/jetstream-backup/snapshots                     
upload failed: ./license.txt to s3://supercdms-data/jetstream-backup/snapshots An error occurred (QuotaExceeded) when calling the PutObject operation: Unknown
```

Can you please investigate?

The backups occupy about half a GB:

```
> aws s3 --profile osn ls supercdms-data/jetstream-backup --recursive --human-readable --summarize
Total Objects: 725 
   Total Size: 544.9 MiB
```

**Comment by pibion** [comment]
@zonca apologies, this is totally a quota issue.  We just got approved for an increase in space and I thought it had "gone through" but clearly it hasn't.  I'll email the OSN folks and cc you so you know what the status is.

**Comment by zonca** [comment]
ok, quota issue is solved, backups worked fine for a few days. Today there are networking issues at IU, so I'll check again in a couple of days. But this specific issue is solved.
