### ISSUE TITLE
host a database on XSEDE and access from jupyter environment?

### ISSUE THREAD

**Issue by pibion** [det-lab/jupyterhub-deploy-kubernetes-jetstream#61]
We have a large database that has metadata for a large chunk of data and it's necessary for analysis.  Does XSEDE host databases?  And would it be possible to access that within our CDMS environment?

I've also reached out to the OSN to see if they have a service that would help here!

**Comment by pibion** [comment]
Update: the OSN does not have a service that helps with this (although I have heard that they can run containers, so maybe with more effort it'd be possible).

**Comment by zonca** [comment]
It would be quite straightforward and also flexible to deploy a container
inside kubernetes with a postgresql database.
However, let me first ask if Jetstream has already a hosted solution.

What are the requirements in terms of storage? Just order of magnitude.
Few GB, few hundreds of GB, or few TB?

Is there any other specific requirement on the database? Do you need
redundancy? High availability? Backup?

**Comment by zonca** [comment]
Also are you really running database operations like join queries? Or could
you store that data  into object store?

**Comment by pibion** [comment]
The types of queries we run tend to be FOR VALUE IN RANGE(LOW, HI) RETURN TEMP1.  The structure of the database is a set of simple tables, each with many fields.  We tend to be querying only one of those tables at a time.  Does that sound like it would work in object store?

The storage requirement is order hundreds of GB.

We have backup elsewhere.  High availability and support for many connections would be nice, but I'm not sure how many people will be accessing - we might be in the range of 1 to 5 analyzers connecting at any given time.  Database knowledge in our collaboration is slim, though, and people may be making queries that return a large dataset.

**Comment by zonca** [comment]
what about a columnar data format in object store? one of the more optimized is parquet, and you can access it directly with pandas. https://arrow.apache.org/docs/python/parquet.html

Or Zarr https://zarr.readthedocs.io/en/stable/, also easily read with `dask`.

Maybe it is worth doing a test with a typical dataset and compare performance with an existing database.
I think the main concern is if you are accessing tiny pieces of huge files.

**Comment by zonca** [comment]
if it is easier, you can give me a dump of 1 of those tables and 1 Python script with a typical data access pattern and what is the expected performance.
I can then test the columnar data formats.

**Comment by pibion** [comment]
@zonca a columnar data format is an interesting idea!  @thathayhaykid is working on uploading a dump of the entire database to the OSN, would that work for access for you?  We could also do a dump just of the fridge data.  We have two tables that we use primarily.

It's possible we're in the "tiny piece of a huge file" but I suspect we could avoid this easily.  I'll see if I can bring the student who will be using this data for analysis over to this conversation.

**Comment by zonca** [comment]
Sure OSN works. Also a sample script is going to be necessary.
It just needs to access the data, It doesn't need to do the actual data processing.

**Comment by pibion** [comment]
@zonca a script is no problem - it may take a week or two, though.  My group is just starting to look at this data.

The query is pretty simple, though, so I'm not worried this time estimate will slip too much.

**Comment by pibion** [comment]
@sukeerthiD this conversation might be of interest!

**Comment by zonca** [comment]
@pibion any update on this?

**Comment by pibion** [comment]
@zonca SLAC was able to get some of the tables accessible on their system.  @thathayhaykid is working on getting the full database from FNAL (this takes a while because we need someone at FNAL to run the command).

If this can be accessed at SLAC we may not need it web-accessible - I think it makes sense to wait and see.  Should I close this issue and re-open if it turns out we do need it?

**Comment by zonca** [comment]
Better just wait and leave this open for tracking purposes.

**Comment by pibion** [comment]
@zonca we are again seeing a need for this information on jetstream.  It would be ideal to keep it as a database because then we could use the scripts that get the information without modification.

But if you think that hosting it as a file would be significantly easier, we can do that - the operations aren't super complex and I think it's better to have the data available and have to re-write scripts than to get totally stuck because we don't have the data at all.

What do you think about difficulty of hosting a file vs. hosting a database?

**Comment by zonca** [comment]
what database software do you have at SLAC? how are the scripts written (language, framework if any)?

**Comment by zonca** [comment]
ok, good, if you are going through sqlalchemy changing backend database should not be a problem.

so we could install PostgreSQL inside Kubernetes with a volume attached on Jetstream 2.

Then you can dump the content of Oracle either with https://ora2pg.darold.net/start.html or via sqlalchemy, or any other way the Oracle admins recommend to a SQL file I can then import into PostgreSQL.

**Comment by pibion** [comment]
We should be able to get a dumpfile of the first X entries in each table.  This will take me a little while, I'm currently trying to get access to the system with the database.  :/

**Comment by pibion** [comment]
Success!  See file at https://drive.google.com/file/d/1M1ngnhk-I-PtkfcXPF50IxmHiqBL9Cx9/view?usp=sharing.

**Comment by zonca** [comment]
it seems this is a dump from MariaDB and not Oracle. Should I use a MariaDB
container then?

**Comment by pibion** [comment]
@zonca probably, but maybe wait a bit for confirmation?  I'm checking with our database-adjacent folks to make sure MariaDB is what's expected here.

**Comment by pibion** [comment]
@zonca update: the original database is MySQL and we're not yet sure what was used to host it at SLAC (which was where I made the current dumpfile).  How do you feel about trying a MariaDB container?

**Comment by zonca** [comment]
ok,
it is deployed on Jetstream, I've imported the dump, usual notes:

https://zonca.dev/2022/06/mariadb-jetstream2-kubernetes.html

I can connect via `sqlalchemy` and I see the data, I put the notebook in the "secrets" repo because it has the password in clear:

https://github.com/pibion/jupyterhub-deploy-kubernetes-jetstream-secrets/blob/master/mariadb/access_mariadb.ipynb

Anyway it is not accessible from outside.

**Comment by pibion** [comment]
@zonca fantastic, I'll be able to test it on Thursday morning.  The full database is large (80 GB at least?) and its dumpfile is already on the OSN.

**Comment by zonca** [comment]
Can you please copy it to the data folder on Jetstream2?

**Comment by zonca** [comment]
Also how big should I get the volume for? The data is 100 GB enough or it's going to grow more?

**Comment by pibion** [comment]
@zonca yes, I'll copy it to the data folder on Jetstream2.

The data won't grow - it's from an experiment that's been decommissioned (but the data is still being analyzed).  But I'm not sure how large the unpacked file will be.  So maybe 200 GB?

**Comment by pibion** [comment]
@zonca it would be easier to copy the file from the OSN if we have `rclone` available.  I can't seem to find the appropriate Dockerfile (?) to edit, could you point me to it?

**Comment by zonca** [comment]
See https://github.com/det-lab/jupyterhub-deploy-kubernetes-jetstream/blob/master/DEPLOY.md#jupyter-notebook-single-user-image

Consider that there is no more automatic building of the thing, so I will have to build it manually on my machine, push it and then update the deployment.

Anyway, that's the same thing I just did to install the MariaDB drivers.

**Comment by pibion** [comment]
@zonca I think the dumpfile is too large for the remaining space on our data volume!  I tried

```
rclone copy OSN:supercdms-data/backups/SoudanTableDump backups/SoudanTableDump
```

but got the error

```
2022/06/16 23:07:31 ERROR : Attempt 1/3 failed with 1 errors and: multipart copy: write failed: write /cvmfs/data/backups/SoudanTableDump/SoudanTableDump: no space left on device
```

**Comment by zonca** [comment]
how big is it?

**Comment by pibion** [comment]
@zonca just over 115 GB.

**Comment by zonca** [comment]
ok, it is a bit convoluted, I created a volume 150 GB in kubernetes, mounted it in a Python container where I installed the AWS client, now I am downloading the dump.
Next I'll mount that volume to a MariaDB client container and try loading the dump into the DB.

**Comment by zonca** [comment]
@pibion ok, it worked fine, I see 142 million rows in one of the tables, see my test with details on how to connect:

https://github.com/pibion/jupyterhub-deploy-kubernetes-jetstream-secrets/blob/master/mariadb/access_mariadb.ipynb

I'll keep the volume with the dump around in case we need to restore.

**Comment by zonca** [comment]
@pibion can you access the db?

**Comment by zkromerUCD** [comment]
@zonca I was able to run the Jupyter notebook and access the database; the results from my running it look the same as yours.

**Comment by zonca** [comment]
Very good. I will close this issue. If you have any problem or you need some other feature please open a separate issue
