### ISSUE TITLE
Redeploying to Jetstream 2 [was: Stuck on "your server is starting up"]

### ISSUE THREAD

**Issue by pibion** [det-lab/jupyterhub-deploy-kubernetes-jetstream#62]
Spawning a jupyter instance gets stuck in "your server is starting up" mode for more than several minutes and then fails.

**Comment by rahmanole** [comment]
<img width="1225" alt="Screenshot 2022-03-03 at 17 53 53" src="https://user-images.githubusercontent.com/39332899/156673134-74e40014-90a4-462b-a2ff-d0b1a53378ff.png">

**Comment by pibion** [comment]
I did check and there are no other instances running (we get a different error when there aren't enough resources, so this is probably a moot point).

**Comment by zonca** [comment]
The cluster has been up for more than a year and it's really nice that kubernetes has a nice security feature 🤔 where the internal certificates expire after a year...
So I will need some time to figure out how to properly renew the certificates.
I will update here once I'm done.

**Comment by zonca** [comment]
Certificate renewal failed, and by mistake a couple of months ago I overwrote the kubespray cluster management files on my machine, won't happen again, I will now use separate directory trees. So I need to redeploy. Then I can restore files from backup.

Before redeploying, I asked the Jetstream team if Jetstream 2 is available. If it is, I would prefer to redeploy directly there.

**Comment by zonca** [comment]
@pibion Jetstream 2 is in early testing and they can let us in.
Jetstream 1 will be operational until summer, but they will soon encourage transition.

* Is it ok if I request the allocation to be transferred to Jetstream 2?
* I should be able to restore user volumes from OSN. What about the `data` volume, would you like me to back it up to OSN and then re-create on Jetstream 2? Or I'll just provide an empty one?

**Comment by pibion** [comment]
Yes, let's move to Jetstream 2!  If you could re-create the `data` volume on Jetstream 2 that would be ideal.  

It's okay if that fails, though, we can re-populate if necessary.

**Comment by pibion** [comment]
@zonca any success with the authentication on Jetstream 2?

**Comment by zonca** [comment]
Yes! Will try deployment in the next days

**Comment by pibion** [comment]
@zonca that's great news!  I had a student contact me today asking about our jetstream instance being down - he uses it often for code development.  I was unusually happy to get a complaint since it means people are using the system!

**Comment by zonca** [comment]
ok, it's working on Jetstream 2.

I deployed it temporarily on https://supercdms.zonca.dev/, I'll move to the old url in the next days.

I haven't imported any backup yet.

* Can you please write here which user data should I import? the less the better, as I need to manually import each of them.
* I'll also start to import the data container, will let you know when is done.

**Comment by zonca** [comment]
we also have a newer version of Jupyterhub (`JupyterHub 1.5.0 20220317202953`)

**Comment by zonca** [comment]
ok, I started the transfer of all the data from the data volume, it will take a few hours.

**Comment by zonca** [comment]
I think it is better if the users first login to the system, then who wants to have their old data restored, can write me and I can copy the data from the backup into their new volumes.

**Comment by pibion** [comment]
Excellent, I'll have them ping you here if they'd like their backup restored!

**Comment by zkromerUCD** [comment]
@zonca Hi, Zonca - I would like my home directory restored - my username on jetstream is zkromer.

**Comment by zonca** [comment]
sure @zkromerUCD , can you please first login to the system so the new volume is created?

**Comment by zkromerUCD** [comment]
ok, I can do that

**Comment by zonca** [comment]
> ok, I started the transfer of all the data from the data volume, it will take a few hours.

completed, I transferred 318 GB, notice that the IP to access the data volume changed, see the repository

**Comment by pibion** [comment]
@zonca great, I can see the expected files in /cvmfs.  There is some weirdness with `/cvmfs/data/CDMS/Soudan/DMC_V1-5_PhotoneutronSb/Raw/Raw`, not sure if that's an issue with the setup or with how we created the directories.

**Comment by zonca** [comment]
not sure, I just copied everything with `scp -r` from one volume to the other

**Comment by zonca** [comment]
ok, I consider this completed, @pibion if there is any other issue please open a dedicated issue.

For restoring user data, let's use https://github.com/det-lab/jupyterhub-deploy-kubernetes-jetstream/issues/64 instead.

**Comment by zonca** [comment]
@pibion @zkromerUCD we are back at the original URL: https://supercdms.jetstream-cloud.org/
