### ISSUE TITLE
Write permissions on XSEDE

### ISSUE THREAD

**Issue by tjamartin** [det-lab/jupyterhub-deploy-kubernetes-jetstream#66]
Hi there, 
I recently started to use XSEDE on the new Jetstream 2 version, however, I do not have write permissions for the /cvmfs/data directory. @pibion suggested I add an issue to get this resolved. Is it possible to global write permissions on /cvmfs/data?

**Comment by zonca** [comment]
ok, try again now.

**Comment by tjamartin** [comment]
It still doesn't seem to be working for me yet

**Comment by zonca** [comment]
my bad, try again
