### ISSUE TITLE
insufficient cpu error

### ISSUE THREAD

**Issue by pibion** [det-lab/jupyterhub-deploy-kubernetes-jetstream#69]
@zonca, @rahmanole is trying to spin up a full node but is getting the following error:

```
2022-04-28T22:23:20.360543Z [Warning] 0/2 nodes are available: 1 Insufficient memory, 2 Insufficient cpu.
```

Nobody else is using an instance right now.

**Comment by pibion** [comment]
More info: requesting a "default" instance reported the same error.  This may be because another student logged on.

**Comment by pibion** [comment]
When @rahmanole tries to spawn a "tiny" instance while the other student is running a "default" he gets the same error.

**Comment by pibion** [comment]
And another error:

```
2022-04-28T22:35:54.562735Z [Warning] 0/2 nodes are available: 1 Insufficient cpu, 1 Insufficient memory, 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate.
```

**Comment by zonca** [comment]
If you enter with your account, you can check out in the admin panel if
there are leftover instances running.

**Comment by zonca** [comment]
I must have configured improperly the limits

**Comment by pibion** [comment]
@zonca one server is running, when @rahmanole first tried to spawn there were no servers running.

**Comment by zonca** [comment]
@pibion I had several leftover pods from my tests on monitoring the backups and from the backup system itself, see #64
I tested now and both 1 full node and (1 default + 1 tiny) work fine.

So I'll check again tomorrow and try to understand why those completed pods still occupy CPU slots.

Anyway, do you plan more usage, would you like to have another node deployed?

With the new kubernetes version I cannot have users on the master node, so they can only use 1 medium worker node.

**Comment by pibion** [comment]
I don't think we need to deploy another node, it's very rare that two people are working at the same time and when they are we have always been fine with 1 default + 1 tiny.

It would be awesome to have the autoscaling managed, though, was there something we were waiting on with Magnum?

**Comment by zonca** [comment]
ok, currently it seems everything is working fine.
We can even have 2 default sessions running together:

```
  jhub                        jupyter-pibion                                 3 (37%)       0 (0%)      12884901888 (41%)  12884901888 (41%)  67m
  jhub                        jupyter-zonca                                  3 (37%)       0 (0%)      12884901888 (41%)  12884901888 (41%)  27s


Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests           Limits
  --------           --------           ------
  cpu                6475m (81%)        300m (3%)
  memory             26012604416 (83%)  26626319616 (85%)

```

Let's keep the issue open and monitor for 1 or 2 weeks.
