### ISSUE TITLE
Descriptive screen to help people report issues more easily

### ISSUE THREAD

**Issue by pibion** [det-lab/jupyterhub-deploy-kubernetes-jetstream#70]
@zonca when people have trouble with instances spinning up, it would be great if they could also get instructions for filing an issue here.  Is it possible to customize the screen that people see when their instance is starting?

**Comment by zonca** [comment]
I was pleasantly surprised to find out that indeed we can using https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html#hub-templatevars

I deployed it

**Comment by zonca** [comment]
if you would like to customize it further, you can edit:

https://github.com/det-lab/jupyterhub-deploy-kubernetes-jetstream/blob/master/config_standard_storage.yaml#L2

There are also other injection points for this type of messages:

`announcement_login, announcement_spawn, announcement_home, and announcement_logout`

**Comment by pibion** [comment]
@zonca I see your banner, I think this is perfect!  Right now I don't see any additional customization needed, so unless you think it would be helpful I think we can close this issue.

**Comment by pibion** [comment]
I worked through a logon with a new student, and I think we need to add the same banner with

`announcement_login, announcement_spawn, announcement_home`

Can I just add these into the JSON on line 2 of the the file linked above?

**Comment by zonca** [comment]
Correct, there is also `announcement`, which is a quick way to set all of them at once

**Comment by zonca** [comment]
@pibion #71 is deployed,
I wonder if it would be more useful to redirect people to a help page with more information, like:

https://github.com/det-lab/jupyterhub-deploy-kubernetes-jetstream#instructions-for-new-users

Maybe update the page first
