### ISSUE TITLE
Backup failing for rahmanole

### ISSUE THREAD

**Issue by zonca** [det-lab/jupyterhub-deploy-kubernetes-jetstream#74]
@rahmanole it seems like your backups are failing,

the error is:

```
Error:      {"message_type":"error","error":{"Op":"lstat","Path":"/stash-data/.ssh/Traces_GAN/utils.py","Err":13},"during":"archival","item":"/stash-data/.ssh/Traces_GAN/utils.py"} Warning: at least one source file could not be read
```

* is there a reason why you are storing python files inside the `.ssh` folder? that is usually meant just for ssh certificates
* can you check if that file has any strange permission or is broken in some other way?

**Comment by pibion** [comment]
@rahmonole the `.ssh` folder is not the place to have most of your data - let me know if you want some help moving into your home directory?

**Comment by zonca** [comment]
it looks like there were 2 Traces_GAN folders, one in home and one in `.ssh`.

I moved the one in `.ssh` to `~/dot_ssh_Traces_GAN`.

I'll check tomorrow if backup worked.

**Comment by pibion** [comment]
Awesome, thank you.  I'll be working with him this week on getting his .ssh directory cleared out.

**Comment by zonca** [comment]
ok, backups are now working
