### ISSUE TITLE
Updated user Docker image

### ISSUE THREAD

**Issue by zonca** [det-lab/jupyterhub-deploy-kubernetes-jetstream#78]
@pibion I needed to add MariaDB client to the Docker images the users are running, #61 
so I also updated all the Conda packages, it doesn't affect users running from CVMFS Kernels much, except JupyterLab is now fancier!

Anyway please report here any issue related to that.

**Comment by zonca** [comment]
I can rollback easily to previous image if needed.

**Comment by pibion** [comment]
@zonca I don't anticipate any issues, but will report if any arise!  I always enjoy a fancier JupyterLab :)

**Comment by zonca** [comment]
seems fine
