### ISSUE TITLE
user can't delete files in .ssh directory

### ISSUE THREAD

**Issue by pibion** [det-lab/jupyterhub-deploy-kubernetes-jetstream#79]
@pandeylekhraj ran into an interesting permissions issue in the `.ssh` directory.

A command to remove an unneeded folder failed with a "permission denied" error: `rm -rf ~/.ssh/tutorials`.

Meanwhile, `mv ~/.ssh/tutorials .` worked fine!

Not sure if this is expected, wanted to report in case it's not.

**Comment by zonca** [comment]
really strange. I don't think it is worth investigating, so I'll close the issue.
Anyway, it is good to have it tracked in the issues for reference in case some other permission issue comes up later on.
