### ISSUE TITLE
March 2023 supplemental request

### ISSUE THREAD

**Issue by pibion** [det-lab/jupyterhub-deploy-kubernetes-jetstream#85]
I've started the documents for the supplemental request at

https://www.overleaf.com/8712573588tgjkfgfwgjpn 

and 

https://docs.google.com/document/d/1UVmlOnx51QsclG8x2r_bYmWVkAMphRDqGooRR0Bm0EQ/edit

@zonca let me know if you'd like to take a look before I submit?  

Unfortunately the nice documentation that was build up at XSEDE hasn't been recreated on ACCESS that I can see, so I'm assuming the guidelines are the same.  The supplemental request seems to be asking for all three documents, the "main document", the progress report, and the code performance and scaling.

**Comment by zonca** [comment]
@pibion it looks good, usually supplement requests don't need to have a lot of supporting documents.
Code performance and scaling does not apply here.

**Comment by zonca** [comment]
accepted!
